
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "duktueioduxmqrydsmbh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - the
# system just generates the content that would be sent and puts it in a directory.
[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 604800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# For apple oauth on mobile, the app association to link signin on ios
service_id = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

# Vector database for storing embeddings.
[vector]
enabled = false

[functions]
[functions.create-payment]
verify_jwt = true

[functions.mollie-webhook]
verify_jwt = false
