// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duktueioduxmqrydsmbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1a3R1ZWlvZHV4bXFyeWRzbWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzMwNzYsImV4cCI6MjA2MTI0OTA3Nn0.L5rYVAH1PFf1RRtZOVh5weCsCaDV6H6XScISNPnnhCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);